# Generated by Django 4.1.5 on 2023-02-03 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title:')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title:')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title:')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('slug_ru', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('slug_en', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('text', models.TextField(max_length=5000, verbose_name='Description:')),
                ('text_ru', models.TextField(max_length=5000, null=True, verbose_name='Description:')),
                ('text_en', models.TextField(max_length=5000, null=True, verbose_name='Description:')),
                ('photo', models.ImageField(upload_to='ProductsCategory/2023-02-03/', verbose_name='Category photo:')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Products Category',
                'verbose_name_plural': 'Products Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title:')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title:')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title:')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('slug_ru', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('slug_en', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
                ('anons', models.CharField(max_length=300, null=True, verbose_name='Anons:')),
                ('anons_ru', models.CharField(max_length=300, null=True, verbose_name='Anons:')),
                ('anons_en', models.CharField(max_length=300, null=True, verbose_name='Anons:')),
                ('description', models.TextField(max_length=20000, null=True, verbose_name='Description:')),
                ('description_ru', models.TextField(max_length=20000, null=True, verbose_name='Description:')),
                ('description_en', models.TextField(max_length=20000, null=True, verbose_name='Description:')),
                ('details', models.TextField(max_length=20000, null=True, verbose_name='Details:')),
                ('details_ru', models.TextField(max_length=20000, null=True, verbose_name='Details:')),
                ('details_en', models.TextField(max_length=20000, null=True, verbose_name='Details:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Products/2023-02-03/', verbose_name='Product photo:')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('hasDescription', models.BooleanField(default=True, verbose_name='hasDescription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created:')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated:')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_Author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category', to='products.productscategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
